language: erlang

otp_release:
   - 19.3
   - 20.3
   - 21.3
   - 22.3
   - 23.0

script:
  - rebar3 --version
  - rebar3 as test xref
  - rebar3 as test dialyzer
  - rebar3 lint
  - rebar3 fmt
  - rebar3 ct
  - rebar3 cover
