---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [19.3, 20.3, 21.3, 22.3, 23.0]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 --version
      - run: rebar3 as test xref
      - run: rebar3 as test dialyzer
      - run: rebar3 lint
      - run: rebar3 ct
      - run: rebar3 cover
